services:
  postgres:
    image: postgres:16
    container_name: altaska_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: altaska
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: altaska_app
    restart: always
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8080:8080"