<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/mainstyle.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/themeToggle.js" defer></script>
    <script src="/js/gallery.js" defer></script>
    <title>altaska</title>
</head>
<body>
<header>
    <div class="site-title">altaska</div>
    <div class="menu-container">
        <div class="theme-icon-container">
            <img class="theme-toggle" src="/icons/sun.svg" alt="Сменить тему">
        </div>
        <div class="menu">
            <button class="menu-button">Продукт</button>
            <button class="menu-button">Возможности</button>
            <button class="menu-button">Для кого</button>
        </div>
        <div class="language-container">
            <img class="language-toggle" src="/icons/language.svg" alt="Сменить язык">
        </div>
    </div>
    <div>
        <button class="login-button">Войти</button>
        <button class="register-button">Зарегистрироваться</button>
    </div>
</header>
<main>
    <h1>Сервис для управления задачами</h1>
    <div class="content-block">
        <p>
            Представляем вам уникальный бесплатный инструмент<br>
            для управления проектами, который поможет вам организовать<br>
            свою работу на высшем уровне. Наша платформа предлагает<br>
            все необходимые функции: от создания задач и списков задач<br>
            до отслеживания статуса выполнения и управления<br>
            командной работой. Удобный интерфейс и гибкие настройки<br>
            позволят вам настроить свою рабочую среду именно<br>
            под ваши нужды!
        </p>
    </div>
    <div class="gallery-container">
        <button class="prev-button">
            <img src="/icons/button_left_light.svg" alt="Назад" width="64" height="64">
        </button>
        <div class="image-container">
            <img class="current-image" src="/images/coming_soon.jpg" alt="Текущее изображение">
        </div>
        <button class="next-button">
            <img src="/icons/button_right_light.svg" alt="Вперед" width="64" height="64">
        </button>
    </div>
    <div class="content-block">
        <p>
            Возможности:
            <ul>
                <li><strong>Создание и управление проектами:</strong> Легко создавайте проекты,<br>
                    добавляйте описание и следите за их развитием с помощью<br>
                    встроенного журнала активности.<br></li>
                <li><strong>Управление задачами:</strong> Создавайте задачи и подзадачи,<br>
                    назначайте приоритеты и сроки, отслеживайте их выполнение,<br>
                    добавляйте комментарии и файлы для<br>
                    удобного совместного использования.<br></li>
                <li><strong>Командная работа:</strong> Приглашайте членов команды,<br>
                    назначайте роли и управляйте доступами. Общайтесь через<br>
                    комментарии и отслеживайте изменения в реальном времени.<br></li>
                <li><strong>Гибкие настройки:</strong> Настраивайте статусы задач, уровни<br>
                    приоритета и добавляйте теги для удобной фильтрации.<br></li>
                <li><strong>Визуализация:</strong> Используйте диаграммы Ганта для<br>
                    наглядного отслеживания сроков выполнения и взаимосвязей<br>
                    между задачами.</li>
            </ul>
        </p>
    </div>
    <div class="center-button">
        <h2>Попробуйте!</h2>
        <button class="register-button">Зарегистрироваться</button>
    </div>
    <div class="content-block">
        <p>
            Наш продукт идеально подходит для фрилансеров,<br>
            небольших команд и стартапов, которые ищут эффективное<br>
            управление проектами без дополнительных затрат.<br>
            Если вы стремитесь улучшить свою продуктивность,<br>
            оптимизировать работу и эффективно взаимодействовать<br>
            с командой, наш инструмент станет вашим<br>
            незаменимым помощником.
        </p>
    </div>
</main>
<footer>
    <p>
        Разработчик: Бельш А.Е.<br>
        Алтайский государственный технический университет<br>
        Барнаул, 2025
    </p>
</footer>
</body>
</html>