<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/mainstyle.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/themeToggle.js" defer></script>
    <title>Главная</title>
</head>
<body>
<header>
    <div class="site-title">altaska</div>
    <div class="menu-container">
        <div class="theme-icon-container">
            <img class="theme-toggle" src="/icons/sun.svg" alt="Сменить тему">
        </div>
    </div>
    <div>
        <a href="/" class="register-button">Мой профиль</a>
    </div>
</header>
<main>

</main>
<footer>

</footer>
</body>
</html>