<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/mainstyle.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/themeToggle.js" defer></script>
    <script src="/js/gallery.js" defer></script>
    <title>Регистрация</title>
</head>
<body>
<header>
    <div class="site-title">altaska</div>
    <div class="menu-container">
        <div class="theme-icon-container">
            <img class="theme-toggle" src="/icons/sun.svg" alt="Сменить тему">
        </div>
        <div class="language-container">
            <img class="language-toggle" src="/icons/language.svg" alt="Сменить язык">
        </div>
    </div>
    <div>
        <button class="login-button">Войти</button>
        <button class="register-button">Зарегистрироваться</button>
    </div>
</header>
<main>

</main>
<footer>
    <p>
        Разработчик: Бельш А.Е.<br>
        Алтайский государственный технический университет<br>
        Барнаул, 2025
    </p>
</footer>
</body>
</html>